CREATE TABLE "${web_clean_table}" as SELECT formresponse.live_in_england,
         regexp_replace(regexp_replace(upper(trim(formresponse.name.first_name)),'(\\s+)',' '),'[^A-Z \-]','') as first_name,
         regexp_replace(regexp_replace(upper(trim(formresponse.name.middle_name)),'(\\s+)',' '),'[^A-Z \-]','') as middle_name,
         regexp_replace(regexp_replace(upper(trim(formresponse.name.last_name)),'(\\s+)',' '),'[^A-Z \-]','') as last_name,
         regexp_replace(upper(trim(formresponse.support_address.town_city)),'[^A-Z \.\-]','') as city,
         regexp_replace(regexp_replace(upper(trim(formresponse.support_address.building_and_street_line_1)),'(\\s+)',' '),'[^A-Z0-9\\\\ \,\.\-]','') as address_l1,
         regexp_replace(regexp_replace(upper(trim(formresponse.support_address.building_and_street_line_2)),'(\\s+)',' '),'[^A-Z0-9\\\\ \,\.\-]','') as address_l2,
         regexp_replace(upper(trim(formresponse.support_address.county)),'[^A-Z \.\-]','') as county,
         regexp_replace(upper(formresponse.support_address.postcode),'[^A-Z0-9]','') as postcode, 
         regexp_replace(upper(trim(formresponse.nhs_number)),'[^A-Z0-9]','') as nhs_number,
         upper(trim(formresponse.carry_supplies)) as carry_supplies,
         regexp_replace(upper(trim(formresponse.reference_id)),'[^A-Z0-9\-]','') as reference_id,
         lpad(trim(formresponse.date_of_birth.day),2,'0') as dob_day,
         lpad(trim(formresponse.date_of_birth.month),2,'0') as dob_month,
         trim(formresponse.date_of_birth.year) as dob_year,
         concat(trim(formresponse.date_of_birth.year),'-',lpad(trim(formresponse.date_of_birth.month),2,'0'),'-',lpad(trim(formresponse.date_of_birth.day),2,'0')) as full_dob,
         formresponse.session_id,
         formresponse._csrf_token,
         regexp_replace(formresponse.contact_details.phone_number_calls,'[^0-9]','') as phone_number_calls,
         regexp_replace(formresponse.contact_details.phone_number_texts,'[^0-9]','') as phone_number_texts,
         trim(formresponse.contact_details.email) as contact,
         upper(trim(formresponse.know_nhs_number)) as know_nhs_number,
         formresponse.check_answers_seen as check_answers_seen,
         upper(trim(formresponse.nhs_letter)) as nhs_letter,
         upper(trim(formresponse.basic_care_needs)) as basic_care_needs,
         upper(trim(formresponse.dietary_requirements)) as dietary_requirements,
         upper(trim(formresponse.medical_conditions)) as medical_conditions,
         upper(trim(formresponse.essential_supplies)) as essential_supplies,
         updated_at,
         referenceid,
         unixtimestamp,
         created_at
FROM "${web_table}"
